version: '3'

services:
  db-server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root@1234
    ports:
      - "3307:3306"
    networks:
      - consumer-producer
      
networks:
  consumer-producer: